blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^blog/$', views.IndexView.as_view(), name='index'),
    url(r'^blog/article/(?P<article2_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^blog/category/(?P<cate_id>\d+)$', views.CategoryView.as_view(), name='category'),
]
"""
    url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<cate_id>\d+)$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    url(r'^archive/(?P<year>\d+)/(?P<month>\d+)$', views.ArchiveView.as_view(), name='archive'),
    url(r'^article/(?P<article_id>\d+)/comment/$', views.CommentPostView.as_view(), name='comment'),
"""
"""
   url(r'^article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<cate_id>\d+)$', views.CategoryView.as_view(), name='category'),
"""

my_blog/urls.py
# -*- coding: utf-8 -*-
"""my_blog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import patterns, include, url
from django.contrib import admin
from blog  import views

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^$',  'article.views.home',  name='home'),
    url(r'^(?P<id>\d+)/$', 'article.views.detail', name='detail'),
    url(r'^test/$', 'article.views.test'),
    url(r'^archives/$', 'article.views.archives', name = 'archives'),
    url(r'^aboutme/$', 'article.views.about_me', name = 'about_me'),
    url(r'^tag/(?P<tag>\w+)/$', 'article.views.search_tag', name = 'search_tag'),
    url(r'^search/$','article.views.blog_search', name = 'search'),
    url(r'^feed/$',  'article.views.RSSFeed', name = "RSS"),
)

"""
    url(r'^blog', views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<article2_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^category/(?P<cate_id>\d+)$', views.CategoryView.as_view(), name='category'),



    url(r'^blog/', include('blog.urls')),
"""

blog/models.py
#coding:utf-8
from django.db import models

# Create your models here.
class Article2(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
    )

    title = models.CharField('标题', max_length=70)
    body = models.TextField('正文')
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES)
    abstract = models.CharField('摘要', max_length=54, blank=True, null=True, 
                                help_text="可选，如若为空将摘取正文的前54个字符")
    views = models.PositiveIntegerField('浏览量', default=0)
    likes = models.PositiveIntegerField('点赞数', default=0)
    topped = models.BooleanField('置顶', default=False)

    category = models.ForeignKey('Category', verbose_name='分类', 
                                 null=True, 
                                 on_delete=models.SET_NULL)

    def __unicode__(self):
    #def __str__(self):
        return self.title

    class Meta:
        ordering = ['-last_modified_time']


class Category(models.Model):
    name = models.CharField('类名', max_length=20)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)

    
    def __unicode__(self):
    #def __str__(self):
        return self.name

blog/views.py
#coding:utf-8
from blog.models import Article2
from blog.models import Category
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView
import markdown2

class IndexView(ListView): 
    """
    首页视图,继承自ListVIew，用于展示从数据库中获取的文章列表
    """

    template_name = "blog/index.html"
    # template_name属性用于指定使用哪个模板进行渲染

    context_object_name = "article2_list"
    # context_object_name属性用于给上下文变量取名（在模板中使用该名字）

    def get_queryset(self):
        """
        过滤数据，获取所有已发布文章，并且将内容转成markdown形式
        """
        article2_list = Article2.objects.filter(status='p')
        # 获取数据库中的所有已发布的文章，即filter(过滤)状态为'p'(已发布)的文章。
        for article2 in article2_list:
            article2.body = markdown2.markdown(article2.body, )
            # 将markdown标记的文本转为html文本
        return article2_list

    def get_context_data(self, **kwargs):
            # 增加额外的数据，这里返回一个文章分类，以字典的形式
        kwargs['category_list'] = Category.objects.all().order_by('name')
        return super(IndexView, self).get_context_data(**kwargs)

class ArticleDetailView(DetailView):
# Django有基于类的视图DetailView,用于显示一个对象的详情页，我们继承它
    model = Article2
    # 指定视图获取哪个model

    template_name = "blog/detail.html"
    # 指定要渲染的模板文件

    context_object_name = "article2"
    # 在模板中需要使用的上下文名字

    pk_url_kwarg = 'article2_id'
    # 这里注意，pk_url_kwarg用于接收一个来自url中的主键，然后会根据这个主键进行查询
    # 我们之前在urlpatterns已经捕获article_id

    # 指定以上几个属性，已经能够返回一个DetailView视图了，为了让文章以markdown形式展现，我们重写get_object()方法。
    def get_object(self):
        obj = super(ArticleDetailView, self).get_object()
        obj.body = markdown2.markdown(obj.body)
        return obj


class CategoryView(ListView):
    template_name = "blog/index.html"
    context_object_name = "article2_list"

    def get_queryset(self):
        article2_list = Article2.objects.filter(category=self.kwargs['cate_id'], status='p')
        for article2 in article2_list:
            article2.body = markdown2.markdown(article2.body, extras=['fenced-code-blocks'], )
        return article2_list

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        return super(CategoryView, self).get_context_data(**kwargs)

class ArticleDetailView(DetailView):
    model = Article2
    template_name = "blog/detail.html"
    context_object_name = "article2"
    pk_url_kwarg = 'article2_id'

    def get_object(self, queryset=None):
        obj = super(ArticleDetailView, self).get_object()
        obj.body = markdown2.markdown(obj.body, extras=['fenced-code-blocks'], )
        return obj

blog/templates/blog/comment.html
<div class="comment">
    <div class="comment-main">
        <p class="head">评论详情</p>
        <form method="post" action="/">
            {% csrf_token %}
            <div class="row">
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <br>
                {% endfor %}
            </div>
            <button type="submit" class="com-button">评论</button>
        </form>
        <p class="comment-count">共{{ 0 }}条评论</p>
        <!--
        <hr>
        {% for comment in comment_list %}
            <div class="main-content">
{#                <img src="月英1.jpg" class="user-avatar">#}
                <span class="user-nickname">{{ comment.user_name }}</span>
                <time class="time">{{ comment.created_time }}</time>
                <div class="comment-content">
                    {{ comment.body }}
                </div>
{#                <a href="">回复</a>#}
            </div>
            <hr>
            -->
        {% endfor %}
    </div>
</div>

blog/templates/blog/detail.html
{% extends 'base2.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div id="bd" class="wrp clear-fix">
                <div id="main">
                    <div id="detail-title">
                        <ul id="single-nav">
                            <li><a href="{% url 'blog:index' %}">首页</a></li>
                            <li>&gt;</li>
                            <li>
                                <ul class="post-categories">
                                    <li><a href="" title=""
                                           rel="category">{{ article2.category.name }}</a>
                                    </li>
                                </ul>
                            </li>
                            <li>&gt;</li>
                            <li class="title-active"><a href="{% url 'detail' article2.pk %}"
                                                        rel="bookmark">{{ article2.title }}</a>
                            </li>
                        </ul>
                    </div>
                    <div id="post-1951"
                         class="post-1951 post type-post status-publish format-standard hentry category-meida-report">
                        <div class="post-hd">
                            <h1 class="title">{{ article2.title }}</h1>
                        </div>
                        <div class="date-read">
                            <i class="icon-date"></i><span
                                class="date">{{ article2.last_modified_time|date:"Y年n月d日" }}</span>
                        </div>
                        <div class="post-bd">
                            {{ article2.body |safe }}
                        </div>
                    </div>
                </div>
            </div>
            {% include 'blog/comment.html' %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base2.html' %}
{% block content %}
    <div id="banner" class="noselect"></div>

    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div id="category" class="noselect">
                    <div id="category-title">
                        <ul>
                            <li>分类：</li>
                            {% for category in category_list %}
                                <li class="cat-item">
                                <a href='{% url 'blog:category' category.pk %}'>{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div id="bd" class="wrp clear-fix">
                    <div id="main">
                        {% load paginate_tags %}
                        {% paginate article2_list 2 %}
                        {% for article2 in article2_list %}
                            <div class="post">
                                <div class="post-hd">
                                    <h1 class="title"><a
                                            href="{% url 'blog:detail' article2.pk %}">{{ article2.title }}</a></h1>
                                </div>
                                <div class="post-bd">
                                    <!-- 	<p><a href=""><img src="" alt=""></a></p> -->
                                    <p>{{ article2.abstract }}</p>
                                    <p><a href="" class="more-link"></a></p>
                                </div>
                                <div class="post-ft">
                                    <a href="/" class="more">阅读全文>></a>
                                    <i class="icon-date"></i>
                                    <span class="date">{{ article.last_modified_time|date:"Y年n月d日" }}</span>
                                </div>
                            </div>
                        {% endfor %}
                        {% include 'blog/pagination.html' %}
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <!-- tags -->
                <h3>标签:</h3>
                <div class="list-group">
                    {% for tag in tag_list %}
                        <a href="{% url 'blog:tag' tag.pk %}" class="list-group-item"><span
                                class="badge"></span>{{ tag.name }}</a>
                    {% endfor %}
                </div>

                <!-- archive -->
                <h3>文章归档：</h3>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    {% for year,months in date_archive %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{ forloop.counter }}">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                       href="#collapse{{ forloop.counter }}"
                                       aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                                        {{ year }} 年
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="heading{{ forloop.counter }}">
                                <div class="panel-body">
                                    {% for month in months %}
                                        <a href="{% url 'blog:archive' year month %}"><p>{{ month }} 月</p></a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/pagination.html
<div id="pagenavi" class="noselect">
    {% if article_list.has_previous %}
        <a class="previous-page" href="?page={{ article_list.previous_page_number }}">
            <span class="icon-previous"></span>上一页
        </a>
    {% endif %}

    {% if first_page == current_page %}
        <span class="first-page current">1</span>
    {% else %}
        <a href="?page=1" class="first-page">1</a>
    {% endif %}

    {% if pages_first > 2 %}
        <span>...</span>
    {% endif %}

    {% for page in pages %}
        {% if page == current_page %}
            <span class="current">{{ page }}</span>
        {% else %}
            <a href="?page={{ page }}">{{ page }}</a>
        {% endif %}
    {% endfor %}

    {% if pages_last < last_page %}
        <span>...</span>
    {% endif %}

    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <span class="current">{{ last_page }}</span>
        {% else %}
            <a href="?page={{ last_page }}">{{ last_page }}</a>
        {% endif %}
    {% endif %}

    {% if article_list.has_next %}
        <a class="next-page" href="?page={{ article_list.next_page_number }}">
            下一页<span class="icon-next"></span>
        </a>
    {% endif %}
</div>